name = "grist-dsfr-form"
main = "worker/index.js"
compatibility_date = "2024-01-01"

# Décommentez et ajustez pour utiliser un domaine custom :
# routes = [
#   { pattern = "formulaire.mondomaine.fr", custom_domain = true }
# ]
